development:
  adapter: postgresql
  encoding: utf8
  database: dezhou_poker
  pool: 1
  username: jeffrey
  password: hero2000
  host: 127.0.0.1
  port: 5432

production:
  adapter: postgresql
  encoding: utf8
  database: dezhou_poker
  pool: 1
  username: jeffrey
  password: hero2000
  host: 127.0.0.1
  port: 5432
